function result = char_eq(l)
    par = struct('k', 1.5, 'D', 0.05, 'v', 1, 'tau', 0.8, 'R', 0.6);
    result = ...
        par.D * eig_fun_1_prime(0, l) ...
        - par.v * eig_fun_1(0, l) ...
        + par.R * par.v * eig_fun_2(0, l);